services:
  postgres:
    image: timescale/timescaledb:latest-pg18@sha256:42ffa71e12b69a7d8ff4fd04c177e4519f66d3c9d1a026e5c4adf296a8168240
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/db-data/:/var/lib/postgresql/
      # - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest@sha256:10137f33be7ed61e47f56004493710cb5b80ba7fb0ca01758855e242f1f284a7
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - postgres-network
    volumes:
      - ${PWD}/.local/pgadmin-data/:/var/lib/pgadmin/
    post_start:
      - command: chown --recursive 5050:0 /var/lib/pgadmin/
        user: root

networks:
  postgres-network:
    driver: bridge
